ACTIVATE := source venv/bin/activate &&

run:
	$(ACTIVATE) python manage.py runserver

migrate:
	$(ACTIVATE) python manage.py migrate

makemigrations:
	$(ACTIVATE) python manage.py makemigrations

collectstatic:
	$(ACTIVATE) python manage.py collectstatic
